default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 1
      recurring_tasks:
        scoop_round:
          class: ScoopPopJob
          schedule: every 2 minutes
  workers:
    - queues: "*"
      threads: 3
      polling_interval: 0.5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
